### ISSUE TITLE
Not all interface names are handled

### ISSUE THREAD

**Issue by Satharus** [ctrivinoe/waspcap#4]
For example my system has: 

eno1, virbr0, and virbr0-nic which don't seem to have entries.

https://github.com/ctrivinoe/waspcap/blob/0527bde86cfaaad0c1e74a1a60e3b0f84488bf31/control_management_pcap.c#L174-L182

The checking method could be done using `strncmp` instead of incrementing the pointer each time. This will result in cleaner code too.

**Comment by ctrivinoe** [comment]
ohh, yeah thx! It was the initial thing I did and I did not know how to use the str methods well, even so I think that for now it will be better to remove the filter and leave it as something indicated since each model will have its interfaces :) then i correct it!
